name: ci-python

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  ci-python:
    uses: PeopleForBikes/.github/.github/workflows/ci-python.yml@main
