name: ci-rust

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  ci-rust:
    uses: PeopleForBikes/.github/.github/workflows/ci-rust.yml@main
